export const ENDPOINTS = {
  LOGIN: "api/auth/login-signup",
  OTP_VERIFY: "api/auth/verify-otp",
  PREFERENCES: "api/auth/register-user-info",
  GET_PROFILE: "api/app/auth/get-profile",
  UPDATE_PROFILE: "api/app/auth/update-profile",
  NINE_NINE_PRODUCTS: "api/products/budget",
  PRODUCTS: "api/products",
  CATEGORY: "api/categories",
  RESTAURANTS: "api/products",
  RESTAURANT_PRODUCTS: "api/restaurant/",
  ALL_RESTAURANTS: "api/restaurant",
  CREATE_ORDER: "/api/app/auth/create-order",
  ADD_ADDRESS: "api/auth/address",
  GET_ADDRESS: "api/auth/address",
  UPDATE_ADDRESS: "api/auth/address",
  NEAR_BY_RESTUARANT: "api/app/auth/nearby-restaurants",
  PROFILE: "api/auth/profile",
  EDIT_PROFILE: "api/auth/profile",
  GET_COUPONS:"api/coupons",
  VALIDATE_COUPON: "api/coupons/validate",
  PLACE_ORDER: "api/orders",
  ADD_CART:"/api/app/auth/add-to-cart",
  HIGH_PROTEIN: "api/high-protein",
  FETCH_MENU: "api/app/restaurants/",
  FETCH_ORDERS: "api/app/orders/user/",
};
