export enum Routes { 
    Login = 'Login',
    PersonalDetails='PersonalDetails',
     MainApp = 'MainApp',
    RestaurantDetails = 'RestaurantDetails',
    LocationSearch = 'LocationSearch',
    SearchProduct="SearchProduct",
    Profile = 'Profile',
    EditProfile="EditProfile",
    OrderDetails="OrderDetails",
    OrderTracking="OrderTracking",
    Settings = 'Settings',
    Dashboard = 'Dashboard',
    Notifications = 'Notifications',
    About = 'About',
    Contact = 'Contact',
    Help = 'Help',
    Terms = 'Terms',
    Privacy = 'Privacy',
    // Add more routes as needed
}